Add user
WildCodeSchool/sept2019-java-tours-SerialSeries pull request #2
Opened 2019-11-18 15:53 UTC by emixaMT

2019-11-18 16:28 UTC, RomainClair commented
- Description de la demande manquante
- Instructions d'installation manquante (n'y aurait-il pas besoin d'une base de donnée ?!?)
- D'ailleurs vérifications lors du traitement du formulaire manquantes (lorsque j'essaye de valider le formulaire, je reviens sur le formulaire sans aucun message d'erreur et je ne constate aucun changement...

2019-11-20 10:18 UTC, emixaMT commented
Here is the local address to launch the app: http://localhost:8080/users

2019-11-20 15:33 UTC, RomainClair requested changes
The README.md lack the database creation instructions.
The dump.sql should probably be imported using the new user instead of root
The import fail with : 
ERROR 1100 (HY000) at line 103: Table 'serie' was not locked with LOCK TABLES

2019-11-21 08:59 UTC, RomainClair approved these changes
- Total lack of comments !! should not pass PR will probably block the next PR
- Inconsistent attribute names (User.pictures should be User.picture)
- Configuration should be in separated files
- Website should have a / URL (home)
To fix for the next PR

2019-11-21 09:00 UTC, merged